structure(list(method = "POST", url = "osm.org/api/0.6/ways", 
    status_code = 409L, headers = structure(list(date = "REDACTED", 
        `content-type` = "text/plain; charset=utf-8", `cache-control` = "no-cache", 
        vary = "Accept,Origin", `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        `referrer-policy` = "strict-origin-when-cross-origin", 
        `x-permitted-cross-domain-policies` = "none", `x-xss-protection` = "0", 
        error = "The user doesn't own that changeset", `x-request-id` = "REDACTED", 
        `x-runtime` = "0.033664", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", `content-security-policy` = "default-src 'self'; child-src 'self'; connect-src 'self' matomo.openstreetmap.org; font-src 'none'; form-action 'self'; frame-ancestors 'self'; frame-src 'self'; img-src 'self' data: www.gravatar.com *.wp.com tile.openstreetmap.org gps.tile.openstreetmap.org *.tile.thunderforest.com tile.tracestrack.com *.openstreetmap.fr matomo.openstreetmap.org https://openstreetmap-user-avatars.s3.dualstack.eu-west-1.amazonaws.com https://openstreetmap-gps-images.s3.dualstack.eu-west-1.amazonaws.com; manifest-src 'self'; media-src 'none'; object-src 'self'; script-src 'self' matomo.openstreetmap.org 'nonce-gurxve5UfDhshiBtT8rjNIWZEDwRNmOa'; style-src 'self' 'nonce-gurxve5UfDhshiBtT8rjNIWZEDwRNmOa'; worker-src 'none'", 
        `x-powered-by` = "Phusion Passenger(R) 6.0.27", status = "409 Conflict", 
        `cf-cache-status` = "DYNAMIC", `report-to` = "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=REDACTED\"}],\"group\":\"cf-nel\",\"max_age\":604800}", 
        nel = "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}", 
        server = "cloudflare", `cf-ray` = "REDACTED", 
        `alt-svc` = "h3=\":443\"; ma=86400", `server-timing` = "cfL4;desc=\"?proto=TCP&REDACTED\""), class = "httr2_headers"), 
    body = charToRaw("The user doesn't own that changeset"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
